version: '3.8'
services:
  backend:
    build: ./server
    ports:
      - "5001:5001"
    environment:
      - MONGO_URL=mongodb://mongo:27017/crassist
    depends_on:
      - mongo

  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: