global:
  scrape_interval: 15s  # How often to scrape targets by default

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'crassist-backend'
    static_configs:
      - targets: ['backend:5001']  # This points to the Node.js metrics endpoint inside Docker
