name: Trivy Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Trivy (latest)
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Scan Docker Image
        run: |
          docker build -t myapp:latest ././client
          trivy image --exit-code 1 --severity CRITICAL myapp:latest

      - name: Scan Terraform Configs
        run: |
          trivy config ./. --exit-code 1 --severity CRITICAL

      - name: Scan for Secrets
        run: |
          trivy fs . --scanners secret --exit-code 0
